<?php
/**
 * Plugin Name: AMJ Gebetstracker
 * Description: Tablet-optimierte Erfassung und Auswertung der Gebetsbesucherzahlen für AMJ Nidda mit Dashboard und PDF-Export.
 * Version: 1.0.0
 * Author: Auto-generated by GPT-5.1-Codex-Max
 */

if (!defined('ABSPATH')) {
    exit;
}

class AMJ_Gebetstracker
{
    private const NONCE_ACTION = 'amj_gebetstracker';
    private const SHORTCODE = 'amj_gebetstracker';

    private array $prayers = [
        [
            'id' => 'fajr',
            'name' => 'Fajr',
            'time' => '06:30',
            'label' => 'Morgen',
        ],
        [
            'id' => 'zohr',
            'name' => 'Zohr',
            'time' => '13:30',
            'label' => 'Mittag',
        ],
        [
            'id' => 'assr',
            'name' => 'Assr',
            'time' => '13:30',
            'label' => 'Nachmittag',
        ],
        [
            'id' => 'maghrib',
            'name' => 'Maghrib',
            'time' => '16:50',
            'label' => 'Abend',
        ],
        [
            'id' => 'isha',
            'name' => 'Isha',
            'time' => '19:00',
            'label' => 'Nacht',
        ],
        [
            'id' => 'jumma',
            'name' => 'Jumma',
            'time' => '13:15',
            'label' => 'Freitag',
        ],
    ];

    private array $groups = ['Atfal', 'Khuddam', 'Ansar'];

    public function __construct()
    {
        register_activation_hook(__FILE__, [$this, 'install']);
        add_action('wp_enqueue_scripts', [$this, 'enqueue_assets']);
        add_shortcode(self::SHORTCODE, [$this, 'render_shortcode']);
        add_action('wp_ajax_amj_save_entry', [$this, 'handle_save_entry']);
        add_action('wp_ajax_nopriv_amj_save_entry', [$this, 'handle_save_entry']);
        add_action('wp_ajax_amj_get_entries', [$this, 'handle_get_entries']);
        add_action('wp_ajax_nopriv_amj_get_entries', [$this, 'handle_get_entries']);
        add_action('wp_ajax_amj_delete_today', [$this, 'handle_delete_today']);
        add_action('wp_ajax_nopriv_amj_delete_today', [$this, 'handle_delete_today']);
    }

    public function install(): void
    {
        global $wpdb;
        $table = $wpdb->prefix . 'gebetstracker_entries';
        $charset = $wpdb->get_charset_collate();

        $sql = "CREATE TABLE {$table} (
            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
            prayer VARCHAR(32) NOT NULL,
            age_group VARCHAR(32) NOT NULL,
            attendees INT UNSIGNED NOT NULL DEFAULT 0,
            entry_date DATE NOT NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY  (id),
            KEY entry_date (entry_date),
            KEY prayer (prayer),
            KEY age_group (age_group)
        ) {$charset};";

        require_once ABSPATH . 'wp-admin/includes/upgrade.php';
        dbDelta($sql);
    }

    private function is_shortcode_present(): bool
    {
        global $post;
        return $post instanceof WP_Post && has_shortcode((string) $post->post_content, self::SHORTCODE);
    }

    public function enqueue_assets(): void
    {
        if (!is_singular() || !$this->is_shortcode_present()) {
            return;
        }

        wp_enqueue_style(
            'amj-gebetstracker',
            plugins_url('styles.css', __FILE__),
            [],
            filemtime(plugin_dir_path(__FILE__) . 'styles.css')
        );

        wp_enqueue_script(
            'jspdf',
            'https://cdn.jsdelivr.net/npm/jspdf@2.5.1/dist/jspdf.umd.min.js',
            [],
            '2.5.1',
            true
        );

        wp_enqueue_script(
            'amj-gebetstracker',
            plugins_url('script.js', __FILE__),
            ['jspdf'],
            filemtime(plugin_dir_path(__FILE__) . 'script.js'),
            true
        );

        wp_localize_script('amj-gebetstracker', 'AMJTracker', [
            'ajaxUrl' => admin_url('admin-ajax.php'),
            'nonce'   => wp_create_nonce(self::NONCE_ACTION),
            'prayers' => $this->prayers,
            'groups'  => $this->groups,
        ]);
    }

    public function render_shortcode(): string
    {
        ob_start();
        include plugin_dir_path(__FILE__) . 'templates/gebetstracker-view.php';
        return ob_get_clean();
    }

    public function handle_save_entry(): void
    {
        check_ajax_referer(self::NONCE_ACTION, 'nonce');

        $ageGroup = sanitize_text_field($_POST['ageGroup'] ?? '');
        $prayerId = sanitize_text_field($_POST['prayerId'] ?? '');
        $count    = (int) ($_POST['count'] ?? 0);
        $entryDate = sanitize_text_field($_POST['entryDate'] ?? current_time('Y-m-d'));

        if (!$ageGroup || !$prayerId || $count < 1) {
            wp_send_json_error(['message' => __('Ungültige Eingabe.', 'amj-gebetstracker')], 400);
        }

        if (!in_array($ageGroup, $this->groups, true)) {
            wp_send_json_error(['message' => __('Unbekannte Altersgruppe.', 'amj-gebetstracker')], 400);
        }

        $validPrayerIds = array_map(static fn($p) => $p['id'], $this->prayers);
        if (!in_array($prayerId, $validPrayerIds, true)) {
            wp_send_json_error(['message' => __('Unbekanntes Gebet.', 'amj-gebetstracker')], 400);
        }

        global $wpdb;
        $table = $wpdb->prefix . 'gebetstracker_entries';

        $wpdb->insert(
            $table,
            [
                'prayer'     => $prayerId,
                'age_group'  => $ageGroup,
                'attendees'  => $count,
                'entry_date' => $entryDate,
                'created_at' => current_time('mysql'),
            ],
            ['%s', '%s', '%d', '%s', '%s']
        );

        if ($wpdb->last_error) {
            wp_send_json_error(['message' => $wpdb->last_error], 500);
        }

        wp_send_json_success(['message' => __('Eintrag gespeichert.', 'amj-gebetstracker')]);
    }

    public function handle_get_entries(): void
    {
        check_ajax_referer(self::NONCE_ACTION, 'nonce');

        $range     = sanitize_text_field($_GET['range'] ?? 'day');
        $reference = sanitize_text_field($_GET['reference'] ?? current_time('Y-m-d'));

        $bounds = $this->get_range_bounds($reference, $range);
        if (!$bounds) {
            wp_send_json_error(['message' => __('Ungültiger Zeitraum.', 'amj-gebetstracker')], 400);
        }

        global $wpdb;
        $table = $wpdb->prefix . 'gebetstracker_entries';

        $today = current_time('Y-m-d');
        $todayEntries = $wpdb->get_results(
            $wpdb->prepare(
                "SELECT id, prayer, age_group, attendees, entry_date, DATE_FORMAT(created_at, '%H:%i') as entry_time
                 FROM {$table}
                 WHERE entry_date = %s
                 ORDER BY created_at DESC",
                $today
            ),
            ARRAY_A
        );

        $stats = $wpdb->get_results(
            $wpdb->prepare(
                "SELECT prayer, age_group, SUM(attendees) as total
                 FROM {$table}
                 WHERE created_at BETWEEN %s AND %s
                 GROUP BY prayer, age_group",
                $bounds['start_mysql'],
                $bounds['end_mysql']
            ),
            ARRAY_A
        );

        $summary = $this->build_summary($stats);

        wp_send_json_success([
            'todayEntries' => $todayEntries,
            'summary'      => $summary,
            'rangeLabel'   => $bounds['label'],
        ]);
    }

    public function handle_delete_today(): void
    {
        check_ajax_referer(self::NONCE_ACTION, 'nonce');
        global $wpdb;
        $table = $wpdb->prefix . 'gebetstracker_entries';
        $date = sanitize_text_field($_POST['entryDate'] ?? current_time('Y-m-d'));

        $wpdb->delete(
            $table,
            [ 'entry_date' => $date ],
            [ '%s' ]
        );

        if ($wpdb->last_error) {
            wp_send_json_error(['message' => $wpdb->last_error], 500);
        }

        wp_send_json_success(['message' => __('Heutige Einträge gelöscht.', 'amj-gebetstracker')]);
    }

    private function build_summary(array $rows): array
    {
        $summary = [];
        foreach ($this->prayers as $prayer) {
            $summary[$prayer['id']] = [
                'total'  => 0,
                'groups' => array_fill_keys($this->groups, 0),
            ];
        }

        foreach ($rows as $row) {
            $prayerId = $row['prayer'];
            $group    = $row['age_group'];
            $total    = (int) $row['total'];
            if (!isset($summary[$prayerId])) {
                continue;
            }
            $summary[$prayerId]['total'] += $total;
            if (isset($summary[$prayerId]['groups'][$group])) {
                $summary[$prayerId]['groups'][$group] += $total;
            }
        }

        return $summary;
    }

    private function get_range_bounds(string $reference, string $mode): ?array
    {
        try {
            $tz = wp_timezone();
            $date = new DateTimeImmutable($reference, $tz);
        } catch (Exception $e) {
            return null;
        }

        if ($mode === 'day') {
            $start = $date->setTime(0, 0, 0);
            $end = $date->setTime(23, 59, 59);
            return [
                'start_mysql' => $start->format('Y-m-d H:i:s'),
                'end_mysql'   => $end->format('Y-m-d H:i:s'),
                'label'       => $date->format('d.m.Y'),
            ];
        }

        if ($mode === 'week') {
            $dow = (int) $date->format('N');
            $start = $date->modify('-' . ($dow - 1) . ' days')->setTime(0, 0, 0);
            $end = $start->modify('+6 days')->setTime(23, 59, 59);
            return [
                'start_mysql' => $start->format('Y-m-d H:i:s'),
                'end_mysql'   => $end->format('Y-m-d H:i:s'),
                'label'       => $start->format('d.m.Y') . ' – ' . $end->format('d.m.Y'),
            ];
        }

        if ($mode === 'month') {
            $start = $date->modify('first day of this month')->setTime(0, 0, 0);
            $end = $date->modify('last day of this month')->setTime(23, 59, 59);
            return [
                'start_mysql' => $start->format('Y-m-d H:i:s'),
                'end_mysql'   => $end->format('Y-m-d H:i:s'),
                'label'       => $start->format('F Y'),
            ];
        }

        return null;
    }
}

new AMJ_Gebetstracker();
